import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../alarms/data/alarm_repository.dart';
import '../../../alarms/data/alarm_model.dart';
import '../../../reminders/data/reminder_repository.dart';
import '../../../reminders/data/reminder_model.dart';
import '../services/llm_service.dart';

/// Executor for offline / online actions generated by LLM responses.
class ActionExecutor {
  final Ref ref;

  ActionExecutor(this.ref);

  /// Executes a list of parsed actions against the local/remote repositories.
  Future<void> execute(List<LlmAction> actions) async {
    final alarmRepo = ref.read(alarmRepositoryProvider);
    final reminderRepo = ref.read(reminderRepositoryProvider);

    for (final action in actions) {
      debugPrint('Executing LLM Action: ${action.type} with params: ${action.params}');
      
      try {
        switch (action.type) {
          case 'mark_taken':
            final index = action.params['index'] as int? ?? 0;
            final alarms = await alarmRepo.getAllAlarms();
            final activeAlarms = alarms.where((a) => a.enabled && a.status == 'ATIVO').toList();
            
            AlarmModel? alarm;
            if (index >= 0 && index < activeAlarms.length) {
              alarm = activeAlarms[index];
            } else if (index >= 0 && index < alarms.length) {
              alarm = alarms[index]; // fallback
            }

            if (alarm != null) {
              double? qty;
              if (action.params.containsKey('quantity')) {
                qty = (action.params['quantity'] as num?)?.toDouble();
              } else if (action.params.containsKey('customQty')) {
                qty = (action.params['customQty'] as num?)?.toDouble();
              }
              await alarmRepo.markTaken(alarm.id, customQty: qty);
            }
            break;

          case 'snooze_alarm':
            final index = action.params['index'] as int? ?? 0;
            final minutes = action.params['minutes'] as int? ?? 10;
            final alarms = await alarmRepo.getAllAlarms();
            final activeAlarms = alarms.where((a) => a.enabled && a.status == 'ATIVO').toList();

            AlarmModel? alarm;
            if (index >= 0 && index < activeAlarms.length) {
              alarm = activeAlarms[index];
            } else if (index >= 0 && index < alarms.length) {
              alarm = alarms[index]; // fallback
            }

            if (alarm != null) {
              await alarmRepo.snoozeAlarm(alarm.id, minutes);
            }
            break;

          case 'toggle_alarm':
            final index = action.params['index'] as int? ?? 0;
            final alarms = await alarmRepo.getAllAlarms();
            if (index >= 0 && index < alarms.length) {
              final alarm = alarms[index];
              final targetEnabled = action.params['enabled'] as bool? ?? !alarm.enabled;
              await alarmRepo.toggleAlarm(alarm.id, targetEnabled);
            }
            break;

          case 'remove_alarm':
            final index = action.params['index'] as int? ?? 0;
            final alarms = await alarmRepo.getAllAlarms();
            if (index >= 0 && index < alarms.length) {
              final alarm = alarms[index];
              await alarmRepo.deleteAlarm(alarm.id);
            }
            break;

          case 'add_alarm':
            final times = _parseTimes(action.params);
            final medName = action.params['med_name'] as String? ?? action.params['name'] as String? ?? 'Medicamento';
            final name = action.params['name'] as String? ?? medName;
            final quantity = (action.params['quantity'] as num?)?.toDouble() ?? 1.0;
            final days = _parseDaysParam(action.params['days']);
            final color = action.params['color'] as String? ?? 'blue';
            final type = action.params['type'] as String? ?? 'comprimido';
            final dosage = action.params['dosage'] as String?;
            final startDate = action.params['start_date'] as String?;
            final durationDays = action.params['duration_days'] as int? ?? 0;

            for (final time in times) {
              final newAlarm = AlarmModel(
                id: 0, // Generated locally
                hour: time['hour']!,
                minute: time['minute']!,
                name: name,
                medName: medName,
                enabled: true,
                active: true,
                days: days,
                status: 'PENDENTE',
                color: color,
                quantity: quantity,
                daysQuantity: List.filled(7, 0.0),
                type: type,
                dosage: dosage,
                snoozeMin: 10,
                startDate: startDate,
                durationDays: durationDays,
              );
              await alarmRepo.createAlarm(newAlarm);
            }
            break;

          case 'update_alarm':
            final index = action.params['index'] as int? ?? 0;
            final alarms = await alarmRepo.getAllAlarms();
            if (index >= 0 && index < alarms.length) {
              final alarm = alarms[index];
              
              final updatedName = action.params['name'] as String? ?? alarm.name;
              final updatedMedName = action.params['med_name'] as String? ?? alarm.medName;
              final updatedHour = action.params['hour'] as int? ?? alarm.hour;
              final updatedMinute = action.params['minute'] as int? ?? alarm.minute;
              final updatedQuantity = (action.params['quantity'] as num?)?.toDouble() ?? alarm.quantity;
              
              List<bool> updatedDays = alarm.days;
              if (action.params.containsKey('days')) {
                updatedDays = _parseDaysParam(action.params['days']);
              }
              
              final updatedColor = action.params['color'] as String? ?? alarm.color;
              final updatedType = action.params['type'] as String? ?? alarm.type;
              final updatedDosage = action.params.containsKey('dosage') ? action.params['dosage'] as String? : alarm.dosage;
              final updatedStartDate = action.params.containsKey('start_date') ? action.params['start_date'] as String? : alarm.startDate;
              final updatedDurationDays = action.params['duration_days'] as int? ?? alarm.durationDays;
              
              final updatedAlarm = alarm.copyWith(
                name: updatedName,
                medName: updatedMedName,
                hour: updatedHour,
                minute: updatedMinute,
                quantity: updatedQuantity,
                days: updatedDays,
                color: updatedColor,
                type: updatedType,
                dosage: updatedDosage,
                startDate: updatedStartDate,
                durationDays: updatedDurationDays,
              );
              
              await alarmRepo.updateAlarm(updatedAlarm);
            }
            break;

          case 'add_reminder':
            final title = action.params['title'] as String? ?? 'Novo Lembrete';
            final description = action.params['description'] as String? ?? '';
            
            bool hasTime = action.params['has_time'] == true;
            if (action.params.containsKey('hour') || action.params.containsKey('minute')) {
              hasTime = true;
            }
            
            final hour = action.params['hour'] as int?;
            final minute = action.params['minute'] as int?;
            final period = action.params['period'] as String? ?? '';
            final interval = action.params['interval'] as int? ?? 1;
            
            String startDate = action.params['start_date'] as String? ?? '';
            if (startDate.isEmpty) {
              final now = DateTime.now();
              startDate = "${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}";
            }
            
            final notifyDaysBefore = action.params['notify_days_before'] as int? ?? 0;
            final color = action.params['color'] as String? ?? 'blue';
            
            final reminder = ReminderModel(
              id: 0,
              title: title,
              description: description,
              enabled: true,
              hasTime: hasTime,
              hour: hour,
              minute: minute,
              period: period,
              interval: interval,
              startDate: startDate,
              notifyDaysBefore: notifyDaysBefore,
              color: color,
            );
            
            await reminderRepo.createReminder(reminder);
            break;

          case 'complete_reminder':
            final index = action.params['index'] as int? ?? 0;
            final allReminders = await reminderRepo.getAllReminders();
            final today = DateTime.now();
            final activeReminders = allReminders.where((r) => reminderRepo.isReminderActiveOnDate(r, today)).toList();

            ReminderModel? reminder;
            if (index >= 0 && index < activeReminders.length) {
              reminder = activeReminders[index];
            } else if (index >= 0 && index < allReminders.length) {
              reminder = allReminders[index]; // fallback
            }

            if (reminder != null) {
              await reminderRepo.completeReminder(reminder.id);
            }
            break;

          default:
            debugPrint('Unknown LLM Action type: ${action.type}');
        }
      } catch (e, stack) {
        debugPrint('Error executing LLM Action ${action.type}: $e\n$stack');
      }
    }
  }

  /// Parses multiple potential times inside add_alarm action params.
  List<Map<String, int>> _parseTimes(Map<String, dynamic> params) {
    final List<Map<String, int>> result = [];

    Map<String, int>? parseTimeString(String s) {
      s = s.trim();
      final match = RegExp(r'^(\d{1,2}):(\d{2})$').firstMatch(s);
      if (match != null) {
        final h = int.tryParse(match.group(1)!);
        final m = int.tryParse(match.group(2)!);
        if (h != null && m != null) {
          return {'hour': h, 'minute': m};
        }
      }
      final hOnly = int.tryParse(s);
      if (hOnly != null) {
        return {'hour': hOnly, 'minute': 0};
      }
      return null;
    }

    if (params['times'] != null) {
      final timesVal = params['times'];
      if (timesVal is List) {
        for (final t in timesVal) {
          if (t is String) {
            final parsed = parseTimeString(t);
            if (parsed != null) result.add(parsed);
          } else if (t is Map) {
            final h = t['hour'] as int? ?? t['hour'] as double? ?? 8;
            final m = t['minute'] as int? ?? t['minute'] as double? ?? 0;
            result.add({'hour': h.toInt(), 'minute': m.toInt()});
          }
        }
      } else if (timesVal is String) {
        final parts = timesVal.split(RegExp(r'[,;]|\band\b'));
        for (final part in parts) {
          final parsed = parseTimeString(part);
          if (parsed != null) result.add(parsed);
        }
      }
    }

    if (params['time'] != null) {
      final timeVal = params['time'];
      if (timeVal is String) {
        final parts = timeVal.split(RegExp(r'[,;]|\band\b'));
        for (final part in parts) {
          final parsed = parseTimeString(part);
          if (parsed != null) result.add(parsed);
        }
      } else if (timeVal is List) {
        for (final t in timeVal) {
          if (t is String) {
            final parsed = parseTimeString(t);
            if (parsed != null) result.add(parsed);
          }
        }
      }
    }

    if (result.isEmpty) {
      final hourVal = params['hour'];
      final minVal = params['minute'];

      if (hourVal is List) {
        for (int i = 0; i < hourVal.length; i++) {
          final h = int.tryParse(hourVal[i].toString()) ?? 8;
          int m = 0;
          if (minVal is List && i < minVal.length) {
            m = int.tryParse(minVal[i].toString()) ?? 0;
          } else if (minVal is int) {
            m = minVal;
          } else if (minVal is String) {
            m = int.tryParse(minVal) ?? 0;
          }
          result.add({'hour': h, 'minute': m});
        }
      } else if (hourVal != null) {
        if (hourVal is String && (hourVal.contains(',') || hourVal.contains(';'))) {
          final hours = hourVal.split(RegExp(r'[,;]'));
          for (final hStr in hours) {
            final h = int.tryParse(hStr.trim()) ?? 8;
            result.add({'hour': h, 'minute': 0});
          }
        } else {
          final h = int.tryParse(hourVal.toString()) ?? 8;
          final m = int.tryParse(minVal?.toString() ?? '0') ?? 0;
          result.add({'hour': h, 'minute': m});
        }
      }
    }

    if (result.isEmpty) {
      result.add({'hour': 8, 'minute': 0});
    }

    return result;
  }

  /// Parses weekday mapping parameters.
  List<bool> _parseDaysParam(dynamic daysVal) {
    if (daysVal == null) return List.filled(7, true);
    if (daysVal is List) {
      if (daysVal.isEmpty) return List.filled(7, true);
      if (daysVal.first is bool) {
        final list = daysVal.cast<bool>();
        if (list.length == 7) return list;
        final result = List.filled(7, false);
        for (int i = 0; i < list.length && i < 7; i++) {
          result[i] = list[i];
        }
        return result;
      } else if (daysVal.first is num) {
        final result = List.filled(7, false);
        for (final d in daysVal) {
          final idx = (d as num).toInt();
          if (idx >= 0 && idx < 7) {
            result[idx] = true;
          }
        }
        return result;
      }
    }
    return List.filled(7, true);
  }
}
